AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 512
    Timeout: 15
Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          /draftkings:
            get:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
              x-amazon-apigateway-integration:
                uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDraftKingsDataFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: '200'
                passthroughBehavior: when_no_match
                httpMethod: POST
                contentHandling: CONVERT_TO_TEXT
                type: aws
  GetDraftKingsDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dfs-optimizer/8b409f1f51b0996a45c0dcf382ad0cd0
      Handler: handler.DraftKingsHandler::handleRequest
      Runtime: java8
      Events:
        GetDraftKingsData:
          Type: Api
          Properties:
            Path: /draftkings
            Method: get
            RestApiId:
              Ref: ServerlessRestApi
    GetFanduelDataFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: target/DFS-Optimizer-Web-1.0-jar-with-dependencies.jar
        Handler: handler.FanduelHandler::handleRequest
        Runtime: java8
        Events:
          GetFanduelData:
            Type: Api
            Properties:
              Path: /fanduel/{date}
              Method: get
              RestApiId:
                Ref: ServerlessRestApi
    GetProjectionsDataFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: target/DFS-Optimizer-Web-1.0-jar-with-dependencies.jar
        Handler: handler.ProjectionsHandler::handleRequest
        Runtime: java8
        Environment:
          Variables:
            key: key
            secret: secret
        Events:
          GetProjectionsData:
            Type: Api
            Properties:
              Path: /projections/{sport}
              Method: get
              RestApiId:
                Ref: ServerlessRestApi
Outputs:
  DfsOptimizerApi:
    Description: API Gateway endpoint URL for Prod stage for DFS Optimizer
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
