AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
  ApiKey:
    Type: String
  ApiSecret:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 15
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub "s3://${BucketName}/swagger.yaml"
  GetDraftKingsDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: handler.DraftKingsHandler::handleRequest
      Runtime: java8
      Events:
        GetDraftKingsData:
          Type: Api
          Properties:
            Path: /draftkings
            Method: get
            RestApiId: !Ref MyApi
  GetFanduelDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: handler.FanduelHandler::handleRequest
      Runtime: java8
      Events:
        GetFanduelData:
          Type: Api
          Properties:
            Path: /fanduel
            Method: get
            RestApiId: !Ref MyApi
  GetProjectionsDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: handler.ProjectionsHandler::handleRequest
      Runtime: java8
      Environment:
        Variables:
          key: !Ref ApiKey
          secret: !Ref ApiSecret
      Events:
        GetProjectionsData:
          Type: Api
          Properties:
            Path: /projections
            Method: get
            RestApiId: !Ref MyApi
  GetOptimalLineupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: handler.OptimizerHandler::handleRequest
      Runtime: java8
      Environment:
        Variables:
          key: !Ref ApiKey
          secret: !Ref ApiSecret
      Events:
        GetOptimalLineup:
          Type: Api
          Properties:
            Path: /optimize
            Method: post
            RestApiId: !Ref MyApi