version: 2.0
container_config: &container_config
  working_directory: ~/dfs-optimizer
  docker:
    - image: openjdk:8-jdk-stretch
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get -y -qq update
            apt-get -y -qq install maven
      - run:
          name: Test and Package
          command: |
            TIMESTAMP=$( date +"%Y-%m-%d_%H-%M-%S" )
            sed -i "s/REPLACE_ME_WITH_TIMESTAMP/$TIMESTAMP/g" pom.xml
            mvn clean package
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .
  deploy:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/dfs-optimizer
      - run:
          name: Install SAM CLI
          command: |
            apt -y -qq update
            apt -y -qq install python3.7
            apt -y -qq install python3-pip
            pip3 install --upgrade awscli
            pip3 install --upgrade aws-sam-cli
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2
      - run:
          name: Deploy to AWS
          command: |
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .

workflows:
  version: 2
  deploy_dfs_optimizer_backend:
    jobs:
      - build
      - deploy:
          context: DFS_OPTIMIZER
          filters:
            branches:
              only:
                - kotlin-migration
          requires:
            - build