version: 2
container_config: &container_config
  working_directory: ~/dfs-optimizer
  docker:
    - image: openjdk:8-jdk-stretch
jobs:
  install_backend:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get -y -qq update
            apt-get -y -qq install maven
            mvn --version
      - run:
          name: Run Backend Tests
          command: |
            TIMESTAMP=$(date +%s)
            mvn replacer:replace -Dccih.origin="<version>REPLACE_ME_WITH_TIMESTAMP</version>" -Dccih.target="<version>${TIMESTAMP}</version>"
            mvn clean package
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .
  deploy_backend:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/dfs-optimizer
      - run:
          name: Install SAM CLI
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python-dev
            apt-get -y -qq install python-pip
            pip install --upgrade awscli
            pip install --upgrade aws-sam-cli
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2
      - run:
          name: Deploy to AWS
          command: |
            chmod +x ./deployBackend.sh
            ./deployBackend.sh
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .
  install_frontend:
    <<: *container_config
    steps:
      - run:
          name: Install Frontend Packages
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs
            curl -L https://www.npmjs.com/install.sh | sh
            cd frontend
            npm install
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .
  test_frontend:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/dfs-optimizer
      - run:
          name: Run Frontend Tests
          command: |
            cd frontend
            npm run test
  build_frontend:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/dfs-optimizer
      - run:
          name: Build
          command: |
            cd frontend
            npm run build
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: ./frontend/build
  deploy_frontend:
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/dfs-optimizer
      - run:
          name: Install SAM CLI
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python-dev
            apt-get -y -qq install python-pip
            pip install --upgrade awscli
            pip install --upgrade aws-sam-cli
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2
      - run:
          name: Deploy to AWS
          command: |
            aws cloudfront create-invalidation --distribution-id "${CDN_DISTRIBUTION_ID}" --paths /\*
            aws s3 sync frontend/build "s3://${BUCKET_NAME}" --exclude "precache-manifest*"

workflows:
  version: 2
  deploy_dfs_optimizer:
    jobs:
      - install_backend:
          context: DFS_OPTIMIZER
      - deploy_backend:
          context: DFS_OPTIMIZER
          filters:
            branches:
              only:
                - master
          requires:
            - install_backend
      - install_frontend:
          context: DFS_OPTIMIZER
      - test_frontend:
          requires:
            - install_frontend
      - build_frontend:
          requires:
            - install_frontend
      - deploy_frontend:
          context: DFS_OPTIMIZER
          filters:
            branches:
              only:
                - master
          requires:
            - install_frontend
            - test_frontend
            - build_frontend