version: 2.1
container_config: &container_config
  working_directory: ~/dfs-optimizer
  docker:
    - image: openjdk:8-jdk-stretch
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get -y -qq update
            apt-get -y -qq install maven
      - run:
          name: Test and Package
          command: |
            TIMESTAMP=$( date +"%Y-%m-%d_%H-%M-%S" )
            sed -i "s/REPLACE_ME_WITH_TIMESTAMP/$TIMESTAMP/g" pom.xml
            mvn clean package
      - persist_to_workspace:
          root: ~/dfs-optimizer
          paths: .
  deploy:
    <<: *container_config
    steps:
      - run:
          name: Set Bash Environment
          command: echo "export PATH='$PATH:/root/.local/bin'" >> $BASH_ENV
      - attach_workspace:
          at: ~/dfs-optimizer
      - sam/install
      - run:
          name: Deploy to AWS
          command: |
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh

workflows:
  version: 2
  deploy_dfs_optimizer_backend:
    jobs:
      - build
      - deploy:
          context: DFS_OPTIMIZER
          filters:
            branches:
              only:
                - kotlin-migration
          requires:
            - build